### ISSUE TITLE
Maximum Call Stack exception on HMR

### ISSUE THREAD

**Issue by davidascher** [visvadw/react-redux-toolbox-starter#1]
Hi there.

Just cloning this repo, npm install, npm start, and then testing the hot reload, I find that if I change `home.js`, I get a hot-reload but I also see:

<img width="1202" alt="screenshot 2016-05-05 15 10 10" src="https://cloud.githubusercontent.com/assets/51278/15058852/9b5670b6-12d3-11e6-878b-ac8d9fe08619.png">

**Comment by dxps** [comment]
Hi David,
Indeed, I've noticed that too, but didn't bother to solve it that late in the night.

The problem was that both `--hot`argument to webpack (in package.json) and `HotModuleReplacementPlugin` (in webpack.config.js) were used and this caused a contention.

The latter was commented out and the issue went away.

**Comment by dxps** [comment]
I found an workaround for hot reloading ing CSS files too.
- It looks like that `ExtractTextPlugin` does not work with HMR, so I remove it:

```
{
   test: /(\.scss|\.css)$/,
   // ExtractTextPlugin does not work with HMR, but it will be included in webpack prod config
   // loader: ExtractTextPlugin.extract('style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox')
   loader: 'style!css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap!toolbox?sourceMap'
}
```
- Having this, assets/react-toolbox.css is not delivered (reference to it returned 404). Therefore I made an empty file `assets/react-toolbox.css` as didn't want to have any errors in the console.

And playing around I can confirm that changes in both `app/toolbox-theme.scss` and `app/style.scss` are hot reloaded. This starter was updated to include these changes.
