### ISSUE TITLE
error css loader

### ISSUE THREAD

**Issue by theajr** [visvadw/react-redux-toolbox-starter#2]
ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]**[local]_**[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./~/react-toolbox/lib/commons.scss
Module build failed: 
@import "./colors";
@import "./globals";
@import "./mixins";
@import "~normalize.css";

html {
  font-size: 62.5%;
}

please let me know how to solve this.

**Comment by dxps** [comment]
I am closing this issue since you raised it again in [#3](https://github.com/visvadw/react-redux-toolbox-starter/issues/2) with more details.
