### ISSUE TITLE
Working in Linux but Not working in windows..

### ISSUE THREAD

**Issue by theajr** [visvadw/react-redux-toolbox-starter#3]
I tried this in linux. it's working. But when I try to clone this and install it's showing the following error.. Please provide a solution.

ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]**[local]_**[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./app/app.scss
Module build failed: 
@import "~react-toolbox/lib/commons";
..

```
  File to import not found or unreadable: C:UsersusernameÞsktopreact-redux-toolbox-starter-master
```

pptheme_config.scss
Parent style sheet: stdin
      in C:\Users\username\Desktop\react-redux-toolbox-starter-master\app\app.scss (line 1, column 1)
 @ ./app/app.scss 4:14-249 13:2-17:4 14:20-255

ERROR in ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]**[local]_**[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./~/react-toolbox/lib/commons.scss

**Comment by dxps** [comment]
I'm sorry, but currently I don't have any Windows system to test it.
It seems that the problem is the missing backslash characters (see `C:UsersusernameÞsktopreact-redux-toolbox-starter-master` that it should be `C:\Users\username ...`).

What is the Node.js version you are using?
A quick search on Google may show you similar issues, but nothing close to it.

**Comment by theajr** [comment]
Yes, I tried on google and looks like I am the only one facing the issue. I could see \ is missing. but I don't know why. I tried 1 week with different Webpack configurations, no luck ! So I had to chose Material-UI. It's working fine. If anyone can help me solve this issue, I would love to use react-toolbox as my front end library.

**Comment by dxps** [comment]
Too bad. Let me see if I can find some time this weekend to play with it in a RHEL 7.1 VM.
I will get back to you as soon as I have some updates. Meanwhile, can you tell me the details of your Linux environment (like Linux distro and version, Node.js version)?

**Comment by dxps** [comment]
I gave up using Material UI and React Toolbox in favor of And Design.
For example, see my starter and playground using it [here](https://github.com/visvadw/ant-design-playground).

**Comment by dxps** [comment]
Indeed, on Windows this is a totally mess! 🗑
